import os
import asyncio
import re
import pandas as pd
from pypdf import PdfReader
from autogen_agentchat.agents import AssistantAgent
from autogen_ext.models.openai import OpenAIChatCompletionClient

# ==========================================
# 1. PATHING SETUP
# ==========================================
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT_DIR = os.path.join(SCRIPT_DIR, "output")
EXCEL_FILENAME = "admission_predictions.xlsx"
OUTPUT_PATH = os.path.join(OUTPUT_DIR, EXCEL_FILENAME)

os.makedirs(OUTPUT_DIR, exist_ok=True)


# ==========================================
# 2. OPTIMIZED TOKEN-SAFE RAG TOOL
# ==========================================
async def retrieve_pdf_knowledge_chunks(query_keyword: str) -> str:
    """
    True Agentic RAG Tool: Broadly locates matched cutoff data segments, 
    but drops empty spaces and isolates target rows to maintain a strict low-token 
    payload that respects Groq free-tier TPM ceilings.
    """
    pdf_files = ["2023ENGG_CAP1_CutOff.pdf"]
    matched_lines = []
    
    search_token = str(query_keyword).strip().lower()
    
    # Vocabulary helper normalization inside the retrieval vector stream
    if "computer" in search_token or "cs" in search_token:
        search_token = "comput"
    elif "mechan" in search_token or "mech" in search_token:
        search_token = "mechan"
    elif "civil" in search_token:
        search_token = "civil"
    elif "it" == search_token or "information" in search_token:
        search_token = "information"

    for pdf_path in pdf_files:
        full_path = os.path.join(SCRIPT_DIR, pdf_path)
        if not os.path.exists(full_path):
            continue
            
        try:
            reader = PdfReader(full_path)
            current_college = "Unknown Institution"
            
            for page_num, page in enumerate(reader.pages):
                text = page.extract_text() or ""
                lines = text.split('\n')
                
                # Check if this entire structural block contains relevant context
                if search_token in text.lower():
                    buffer_lines = []
                    for line in lines:
                        line_clean = line.strip()
                        if not line_clean:
                            continue
                            
                        if re.search(r'^\d{4}\s*-', line_clean) or "Institute" in line_clean or "College" in line_clean:
                            current_college = line_clean
                        
                        # Only take data-carrying lines to compress token size drastically
                        if any(k in line_clean.upper() for k in ["STAGE", "OPEN", "OBC", "SC", "ST", "PWD", "MINORITY"]) or search_token in line_clean.lower():
                            buffer_lines.append(f"[{current_college}] {line_clean}")
                    
                    if buffer_lines:
                        matched_lines.append(
                            f"--- CONTENT SECTOR ({pdf_path} | Page: {page_num + 1}) ---\n" + 
                            "\n".join(buffer_lines)
                        )
        except Exception as e:
            return f"Error reading document vectors: {str(e)}"
            
    if not matched_lines:
        return f"No context entries matched the search token: '{search_token}'."
        
    # Join target content tightly (Limit payload block size to avoid going over 12k tokens)
    compressed_payload = "\n\n".join(matched_lines[:5])
    return compressed_payload[:25000] # Safe substring truncation as a final guardrail


# ==========================================
# 3. BACKGROUND EXCEL SPREADSHEET WRITER
# ==========================================
def extract_and_save_excel(agent_response_text: str) -> bool:
    """Parses structural tokens generated by the agent and outputs a clean Excel workbook."""
    lines = agent_response_text.strip().split('\n')
    rows = []
    
    # Captures clean rows from the agent's structural outputs
    pattern = re.compile(r'(?:\*\*|)\s*DATA_ROW\s*:\s*(?:\*\*|)\s*(.*)', re.IGNORECASE)
    
    for line in lines:
        match = pattern.search(line.strip())
        if match:
            clean_line = match.group(1).strip()
            parts = [p.strip() for p in clean_line.split('|')]
            if len(parts) >= 4:
                rows.append({
                    "College Code": parts[0],
                    "College Name": parts[1],
                    "Branch": parts[2],
                    "Reasoning Preference": parts[3]
                })
                
    if rows:
        df = pd.DataFrame(rows)
        df.drop_duplicates(subset=["College Code", "Branch"], inplace=True)
        df.columns = ["College Code", "College Name", "Branch", "Reasoning Preference"]
        df.to_excel(OUTPUT_PATH, index=False, engine='openpyxl')
        return True
    return False


# ==========================================
# 4. AGENTIC FRAMEWORK INITIALIZATION
# ==========================================
async def main():
    # Setup Groq Client
    model_client = OpenAIChatCompletionClient(
        model="llama-3.3-70b-versatile",
        api_key="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",
        base_url="https://api.groq.com/openai/v1",  
        temperature=0.1,
        model_info={
            "vision": False,
            "function_calling": True,
            "json_output": True,
            "family": "unknown"
        }
    )

    # Master Agent System Instructions giving full analytical power to the LLM
    counselor_instructions = """
    ROLE: You are an expert, highly strategic Maharashtra Engineering CAP Counselor Agent.
    
    YOUR AGENTIC INSTRUCTIONS:
    1. PARAMETER ANALYSIS:
       Read the user prompt string, isolate their target choice stream branch, and call `retrieve_pdf_knowledge_chunks`.
    
    2. SMART CATEGORY MAPPING:
       Analyze the raw context rows. Map user keywords to data columns autonomously:
       - 'OBC' checks tokens like 'GOBCS', 'LOBCS', or numbers under OBC rows.
       - 'Open' checks tokens like 'GOPENS', 'LOPENS', etc.
       - If PWD status is 'Yes', prioritize fields containing 'PWD'.
       
    3. PREFERENCE EVALUATION LOGIC:
       Compare the user's score with the closing cutoff found in the document text. Categorize every match using these strict rules:
       - User score is > 3% above historical PDF cutoff: 'Best Option'
       - User score is 1% to 3% above historical PDF cutoff: 'Better Option'
       - User score is within +/- 1% of historical PDF cutoff: 'Good Option'
       - User score is 1% to 2.5% below historical PDF cutoff: 'Average Option'
       
    4. SPREADSHEET OUTPUT DUMP FORMAT:
       You must output your recommendations ONLY as clean structured data tokens so our script can convert them to Excel. Format your rows like this:
       DATA_ROW: [Code] | [Full College Name] | [Branch Title] | [Preference Category]
       
       Provide up to 20 valid choices if available in the retrieved context block. Do not write any conversational summaries.
    """

    counselor_agent = AssistantAgent(
        name="Maharashtra_College_Counselor",
        model_client=model_client,
        system_message=counselor_instructions,
        tools=[retrieve_pdf_knowledge_chunks]
    )

    print("\n==================================================================")
    print("🚀 MAHARASHTRA ENGINEERING ADMISSION AI AGENT ACTIVE")
    print("Input parameters dynamically or ask any direct counseling question.")
    print("==================================================================\n")

    while True:
        user_input = input("\nYou: ")
        if user_input.strip().lower() == 'exit':
            print("Closing session. Good luck with your CAP rounds!")
            break
            
        if not user_input.strip():
            continue

        print("[AGENT WORKFLOW]: Analyzing query parameters and triggering tool call...")
        
        # Run AutoGen Agentic Execution
        response = await counselor_agent.run(task=user_input)
        response_content = response.messages[-1].content
        
        # Save results to Excel workbook file
        success = extract_and_save_excel(response_content)
        
        if success:
            print("✅ [SUCCESS]: Choice list compiled cleanly based on document cutoffs!")
            print(f"📁 Spreadsheet dynamically updated -> {OUTPUT_PATH}\n")
        else:
            print("❌ [AGENT NOTICE]: The agent could not locate matches for those criteria within the data context. Try adjusting your query.\n")

if __name__ == "__main__":
    asyncio.run(main())
